# Generated by Django 3.0.5 on 2020-04-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=50)),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
