# Generated by Django 3.0.5 on 2020-04-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200408_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=350, verbose_name='متن نوشته '),
        ),
    ]
