# Generated by Django 3.0.5 on 2020-04-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200408_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='p_date',
            field=models.DateField(auto_now=True, verbose_name='تاریخ'),
        ),
    ]
