# Generated by Django 3.0.5 on 2020-04-09 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_p_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Blog',
        ),
    ]
